### ISSUE TITLE
ldtk example crashes

### ISSUE THREAD

**Issue by tliron** [443eb9/bevy_entitiles#21]
**Description**

It seems the string "ignore " is prepended to the asset name, causing it to fail to load.

Logs:

```
2024-04-12T20:44:49.206877Z  INFO bevy_winit::system: Creating new window "App" (0v1)
2024-04-12T20:44:49.207397Z  INFO log: Guessed window scale factor: 2    
2024-04-12T20:44:49.332413Z  INFO bevy_render::renderer: AdapterInfo { name: "AMD Radeon RX 6500 XT (RADV NAVI24)", vendor: 4098, device: 29759, device_type: DiscreteGpu, driver: "radv", driver_info: "Mesa 23.3.6", backend: Vulkan }
2024-04-12T20:44:49.363404Z  WARN bevy_inspector_egui::inspector_options::default_options: Attempting to set default inspector options for bevy_pbr::light::AmbientLight, but it wasn't registered in the type registry.
2024-04-12T20:44:49.363425Z  WARN bevy_inspector_egui::inspector_options::default_options: Attempting to set default inspector options for bevy_pbr::light::PointLight, but it wasn't registered in the type registry.
2024-04-12T20:44:49.363429Z  WARN bevy_inspector_egui::inspector_options::default_options: Attempting to set default inspector options for bevy_pbr::light::DirectionalLight, but it wasn't registered in the type registry.
2024-04-12T20:44:49.363434Z  WARN bevy_inspector_egui::inspector_options::default_options: Attempting to set default inspector options for bevy_pbr::pbr_material::StandardMaterial, but it wasn't registered in the type registry.
2024-04-12T20:44:49.363442Z  WARN bevy_inspector_egui::inspector_options::default_options: Attempting to set default inspector options for bevy_pbr::light::ClusterConfig, but it wasn't registered in the type registry.
   0: bevy_ecs::system::function_system::system
           with name="bevy_entitiles::ldtk::parse_ldtk_json"
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.2/src/system/function_system.rs:47
thread 'main' panicked at src/ldtk/resources.rs:379:23:
Could not read file at path: "/Depot/Projects/Gaming/bevy_entitiles/assets/ldtk/ignore grid_vania.ldtk"!
No such file or directory (os error 2)
stack backtrace:
   0: rust_begin_unwind
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panicking.rs:72:14
   2: bevy_entitiles::ldtk::resources::LdtkLevelManager::reload_json
             at ./src/ldtk/resources.rs:379:23
   3: bevy_entitiles::ldtk::parse_ldtk_json
             at ./src/ldtk/mod.rs:152:5
   4: core::ops::function::FnMut::call_mut
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:166:5
   5: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:294:13
   6: <Func as bevy_ecs::system::function_system::SystemParamFunction<fn(F0,F1) .> Out>>::run::call_inner
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.2/src/system/function_system.rs:656:21
   7: <Func as bevy_ecs::system::function_system::SystemParamFunction<fn(F0,F1) .> Out>>::run
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.2/src/system/function_system.rs:659:17
   8: <bevy_ecs::system::function_system::FunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run_unsafe
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.2/src/system/function_system.rs:499:19
   9: bevy_ecs::system::system::System::run
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.2/src/system/system.rs:76:18
  10: <bevy_ecs::schedule::executor::single_threaded::SingleThreadedExecutor as bevy_ecs::schedule::executor::SystemExecutor>::run::{{closure}}
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.2/src/schedule/executor/single_threaded.rs:101:21
  11: core::ops::function::FnOnce::call_once
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:250:5
  12: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panic/unwind_safe.rs:272:9
  13: std::panicking::try::do_call
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:554:40
  14: std::panicking::try
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:518:19
  15: std::panic::catch_unwind
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panic.rs:142:14
  16: <bevy_ecs::schedule::executor::single_threaded::SingleThreadedExecutor as bevy_ecs::schedule::executor::SystemExecutor>::run
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.2/src/schedule/executor/single_threaded.rs:100:27
  17: bevy_ecs::schedule::schedule::Schedule::run
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.2/src/schedule/schedule.rs:345:13
  18: bevy_ecs::world::World::try_run_schedule::{{closure}}
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.2/src/world/mod.rs:2292:55
  19: bevy_ecs::world::World::try_schedule_scope
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.2/src/world/mod.rs:2225:21
  20: bevy_ecs::world::World::try_run_schedule
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.2/src/world/mod.rs:2292:9
  21: bevy_app::main_schedule::Main::run_main::{{closure}}
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.13.2/src/main_schedule.rs:225:35
  22: bevy_ecs::world::World::resource_scope
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.2/src/world/mod.rs:1672:22
  23: bevy_app::main_schedule::Main::run_main
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.13.2/src/main_schedule.rs:223:13
  24: core::ops::function::FnMut::call_mut
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:166:5
  25: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:294:13
  26: <Func as bevy_ecs::system::exclusive_function_system::ExclusiveSystemParamFunction<fn(F0) .> Out>>::run::call_inner
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.2/src/system/exclusive_function_system.rs:206:21
  27: <Func as bevy_ecs::system::exclusive_function_system::ExclusiveSystemParamFunction<fn(F0) .> Out>>::run
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.2/src/system/exclusive_function_system.rs:209:17
  28: <bevy_ecs::system::exclusive_function_system::ExclusiveFunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run::{{closure}}
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.2/src/system/exclusive_function_system.rs:111:23
  29: bevy_ecs::world::World::last_change_tick_scope
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.2/src/world/mod.rs:1981:9
  30: <bevy_ecs::system::exclusive_function_system::ExclusiveFunctionSystem<Marker,F> as bevy_ecs::system::system::System>::run
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.2/src/system/exclusive_function_system.rs:103:9
  31: <bevy_ecs::schedule::executor::single_threaded::SingleThreadedExecutor as bevy_ecs::schedule::executor::SystemExecutor>::run::{{closure}}
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.2/src/schedule/executor/single_threaded.rs:101:21
  32: core::ops::function::FnOnce::call_once
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:250:5
  33: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/panic/unwind_safe.rs:272:9
  34: std::panicking::try::do_call
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:554:40
  35: std::panicking::try
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panicking.rs:518:19
  36: std::panic::catch_unwind
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/std/src/panic.rs:142:14
  37: <bevy_ecs::schedule::executor::single_threaded::SingleThreadedExecutor as bevy_ecs::schedule::executor::SystemExecutor>::run
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.2/src/schedule/executor/single_threaded.rs:100:27
  38: bevy_ecs::schedule::schedule::Schedule::run
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.2/src/schedule/schedule.rs:345:13
  39: bevy_ecs::world::World::run_schedule::{{closure}}
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.2/src/world/mod.rs:2306:51
  40: bevy_ecs::world::World::try_schedule_scope
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.2/src/world/mod.rs:2225:21
  41: bevy_ecs::world::World::schedule_scope
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.2/src/world/mod.rs:2277:9
  42: bevy_ecs::world::World::run_schedule
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_ecs-0.13.2/src/world/mod.rs:2306:9
  43: bevy_app::app::App::update
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.13.2/src/app.rs:263:24
  44: bevy_winit::run_app_update_if_should
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.13.2/src/lib.rs:741:9
  45: bevy_winit::handle_winit_event
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.13.2/src/lib.rs:618:21
  46: bevy_winit::winit_runner::{{closure}}
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.13.2/src/lib.rs:290:9
  47: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:294:13
  48: winit::platform_impl::platform::x11::EventLoop<T>::single_iteration
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/x11/mod.rs:602:17
  49: winit::platform_impl::platform::x11::EventLoop<T>::pump_events
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/x11/mod.rs:441:13
  50: winit::platform_impl::platform::x11::EventLoop<T>::run_on_demand
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/x11/mod.rs:408:19
  51: winit::platform_impl::platform::EventLoop<T>::run_on_demand
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/mod.rs:829:56
  52: winit::platform_impl::platform::EventLoop<T>::run
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/platform_impl/linux/mod.rs:822:9
  53: winit::event_loop::EventLoop<T>::run
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.29.15/src/event_loop.rs:249:9
  54: bevy_winit::winit_runner
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_winit-0.13.2/src/lib.rs:305:34
  55: core::ops::function::FnOnce::call_once
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:250:5
  56: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:250:5
  57: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/alloc/src/boxed.rs:2015:9
  58: bevy_app::app::App::run
             at /home/emblemparade/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bevy_app-0.13.2/src/app.rs:308:9
  59: ldtk::main
             at ./examples/ldtk.rs:52:5
  60: core::ops::function::FnOnce::call_once
             at /rustc/25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Encountered a panic in system `bevy_entitiles::ldtk::parse_ldtk_json`!
2024-04-12T20:44:49.865748Z  WARN bevy_app:winit event_handler:update:main app:schedule{name=Main}: bevy_ecs::system::commands::command_queue: CommandQueue has un-applied commands being dropped.
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

**Reproduction**

```
git checkout 0.7.0
RUST_BACKTRACE=1 cargo run --example ldtk --features=debug,ldtk,physics
```

**Versions**
 - OS: Linux
 - Crate and other dependencies: entitiles: 0.7.0

**Comment by 443eb9** [comment]
Well, that's expected. You need to remove the `ignore` prefix manually. The asset with `ignore` only exists on my pc. But as many of you are confused by this, I will remove it when a new version is released. Thanks for the feedback.
